In [ ]:
# Embedding layer in Keras ? #

# Turns positive integers (indexes) into dense vectors of fixed size.
# e.g. [[4], [20]] -> [[0.25, 0.1], [0.6, -0.2]]
# This layer can only be used on positive integer inputs of a fixed range.

# How does keras converts an interger representation into dense vectors ? #

# Keras converts integer representations into dense vectors using an Embedding layer, which learns an internal embedding matrix
# during the training process.

# Here's a step-by-step explanation of how Keras achieves this transformation:

# 1. Embedding Layer Initialization:
# When you define an Embedding layer in Keras, you specify the input_dim (size of the vocabulary), output_dim (size of the dense vector), and optionally input_length (length of input sequences).
# The Embedding layer initializes an embedding matrix of shape (input_dim, output_dim), where:
# input_dim is the total number of unique words in the vocabulary.
# output_dim is the dimensionality of the dense vector for each word.
# This matrix is usually initialized with small random values (e.g., using a uniform or normal distribution).

# 2. Mapping Integers to Vectors:
# The input to the Embedding layer is a sequence of integers, where each integer represents a word’s index in the vocabulary.
# When a batch of sequences is fed into the Embedding layer, each integer is used as an index to look up the corresponding row in the embedding matrix.
# For example, if the integer 5 is an input value, the Embedding layer retrieves the 5th row from the embedding matrix, which is the dense vector representation of the word corresponding to index 5.

# 3. Embedding Matrix:
# The embedding matrix can be thought of as a lookup table where each row represents the embedding vector for a specific word.
# Initially, these vectors are random, but during training, the neural network adjusts the vectors (i.e., the values in the embedding matrix) through backpropagation to minimize the loss function.
# The training process involves adjusting the embeddings so that they capture semantic similarities and other relevant characteristics of the words in the context of the task.

# 4. Backpropagation and Learning:
# During training, as the model processes batches of data, the embeddings are updated by backpropagating the error gradients from the loss function through the network.
# The embedding vectors are modified in such a way that words with similar meanings or roles in the data (as learned by the network) end up with similar vectors in the embedding space.
# Example of How It Works in Practice:
# Suppose you have the following setup:

# Vocabulary size (input_dim) = 10,000 (words indexed from 0 to 9999).
# Embedding size (output_dim) = 100 (each word will be represented by a 100-dimensional vector).
# Input sequence = [7, 12, 543, 34] (a sequence of word indices).
# Here’s what happens inside the Embedding layer:

# The layer looks up the 7th, 12th, 543rd, and 34th rows of the embedding matrix.
# Each of these rows is a 100-dimensional vector, e.g., [0.01, -0.03, ..., 0.02].
# The output of the Embedding layer for this sequence is a 2D array (or tensor) of shape (4, 100), where 4 is the length of the input sequence and 100 is the embedding dimension.


In [1]:
# import tensorflow as tf
# print(tf.__version__)

2.17.0


In [46]:
import numpy as np
import tensorflow as tf
import os

from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Flatten, Dense

# Set environment variable to suppress TensorFlow warnings
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'


docs = [
        "feeling on top of the world today!",
        "just enjoying the beautiful sunshine",
        "looking forward to this for weeks",
        "literally jumping up and down with excitement",
        "feeling really down and can't seem to shake it off",
        "so frustrated and fed up with this situation",
        "it's all too much to handle."
        ]
labels = np.array([1,1,1,1,0,0,0])
# 1: good mood
# 0: bad mood

# integer encode the documents
vocab = 50
encoded_data = [one_hot(mood,vocab) for mood in docs]
print(encoded_data)

# pad documents to a max length of 4 words
max_pad = 10
padded_data = pad_sequences(encoded_data, maxlen = max_pad , padding="pre")
print("padded data below : ")
print(padded_data)

# define the model
model = Sequential()
model.add(Embedding(vocab,8,input_length = max_pad))
model.add(Flatten())
model.add(Dense(1, activation="sigmoid"))

# complile the model
model.compile(optimizer="adam",loss=['binary_crossentropy'], metrics=['accuracy'])

# fit the model
model.fit(padded_data,labels,epochs=50,verbose=0)

# evaluate the model
loss, accuracy = model.evaluate(padded_data,labels,verbose=0)
print('loss: %f' % (loss))
print('Accuracy: %f' % (accuracy*100))

# summarize the model
print(model.summary())

# embedding model
model_embed = Sequential()
model_embed.add(Embedding(vocab,8,input_length = max_pad))
model_embed.compile(optimizer="adam", metrics=['mse'])

# embedding generated by the embedding model
print(padded_data[0])
print(model_embed.predict(padded_data[0]))

[[13, 36, 22, 18, 41, 32, 7], [15, 30, 41, 33, 10], [2, 2, 28, 3, 42, 27], [32, 36, 48, 20, 25, 13, 22], [13, 40, 25, 20, 20, 36, 28, 31, 37, 33], [22, 11, 20, 25, 48, 13, 3, 45], [48, 13, 33, 31, 28, 34]]
padded data below : 
[[ 0  0  0 13 36 22 18 41 32  7]
 [ 0  0  0  0  0 15 30 41 33 10]
 [ 0  0  0  0  2  2 28  3 42 27]
 [ 0  0  0 32 36 48 20 25 13 22]
 [13 40 25 20 20 36 28 31 37 33]
 [ 0  0 22 11 20 25 48 13  3 45]
 [ 0  0  0  0 48 13 33 31 28 34]]
loss: 0.487917
Accuracy: 100.000000


Model: "sequential_27"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_26 (Embedding)             │ (None, 10, 8)               │             400 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_18 (Flatten)                 │ (None, 80)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_16 (Dense)                     │ (None, 1)                   │              81 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,445 (5.65 KB)

 Trainable params: 481 (1.88 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 964 (3.77 KB)

None
[ 0  0  0 13 36 22 18 41 32  7]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step
[[-3.6137462e-02 -1.2286425e-02 -1.7932914e-02 -5.4373741e-03
  -2.6029874e-02 -1.9452250e-02 -1.5482008e-02  4.8886035e-02]
 [-3.6137462e-02 -1.2286425e-02 -1.7932914e-02 -5.4373741e-03
  -2.6029874e-02 -1.9452250e-02 -1.5482008e-02  4.8886035e-02]
 [-3.6137462e-02 -1.2286425e-02 -1.7932914e-02 -5.4373741e-03
  -2.6029874e-02 -1.9452250e-02 -1.5482008e-02  4.8886035e-02]
 [ 3.0116066e-03  4.2416643e-02  4.8363391e-02 -4.0830769e-02
   2.1161709e-02 -3.8576078e-02  4.0204536e-02 -9.6517801e-04]
 [-4.8366915e-02  2.4129860e-03 -3.6535762e-02  2.9794399e-02
  -2.6119208e-02 -2.4065519e-02  3.4307029e-02 -1.5863895e-02]
 [ 4.0287945e-02  2.1868944e-03 -3.1550504e-02 -4.4279408e-02
   4.9433198e-02 -3.0688310e-02 -3.9046336e-02  3.4235120e-03]
 [-3.7906755e-02  3.6570918e-02  2.4719786e-02 -2.6015533e-02
  -4.2387247e-02  3.0518178e-02  5.7295710e-04 -7.3708594e-05]
 [ 1.7522488e-02  2.9725444e-02  1.6301002e-02  4